//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Dental_Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public long ID_HoaDon { get; set; }
        public Nullable<double> TongTien { get; set; }
        public string Id { get; set; }
        public Nullable<int> Id_GoiDichVu { get; set; }
        public Nullable<int> ID_ThanhToan { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual GoiDichVu GoiDichVu { get; set; }
        public virtual HinhThucThanhToan HinhThucThanhToan { get; set; }
    }
}
