//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Dental_Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        public int IDKHACHHANG { get; set; }
        public string Tenkhachhang { get; set; }
        public string Sdt { get; set; }
        public Nullable<int> IdLich { get; set; }
    
        public virtual LichHen LichHen { get; set; }
    }
}
