//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Booking_Dental_Clinic.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichHen
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LichHen()
        {
            this.KhachHangs = new HashSet<KhachHang>();
        }
    
        public int IdLich { get; set; }
        public string Tenkhachhang { get; set; }
        public int IDBACSI { get; set; }
        public int IDDICHVU { get; set; }
        public string Sdt { get; set; }
        public Nullable<System.DateTime> Ngaydat { get; set; }
        public string Id { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KhachHang> KhachHangs { get; set; }
        public virtual LoaiDichVu LoaiDichVu { get; set; }
        public virtual NhaSi NhaSi { get; set; }
    }
}
